### ISSUE TITLE
Uncaught TypeError: atom.workspace.getActiveEditor is not a function

### ISSUE THREAD

**Issue by ruivieira** [mh61503891/skim-displayline#2]
[Enter steps to reproduce below:]
1. Install the packages: language-latex, latex, latexer, skim-displayline
2. Add displayline to the PATH (as per skim-displayline instructions)
3. Open a valid TeX file, add \synctex=1
4. Compile TeX from Atom with ctrl-alt-b
5. Open PDF in Skim
6. Open palette and choose "Skim: Displayline"

**Atom Version**: 1.5.3
**System**: Mac OS X 10.11.3
**Thrown From**: [skim-displayline](https://github.com/mh61503891/skim-displayline) package, v0.0.1
### Stack Trace

Uncaught TypeError: atom.workspace.getActiveEditor is not a function

```
At /Users/rui/.atom/packages/skim-displayline/lib/skim-displayline.coffee:11

TypeError: atom.workspace.getActiveEditor is not a function
    at Object.module.exports.displayline (/Users/rui/.atom/packages/skim-displayline/lib/skim-displayline.coffee:11:29)
    at atom-workspace.subscriptions.add.atom.commands.add.skim:displayline (/Users/rui/.atom/packages/skim-displayline/lib/skim-displayline.coffee:7:84)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:536:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:359:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:04.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 core:move-down (atom-text-editor.editor.mini.is-focused)
     -0:00.8.0 core:move-up (atom-text-editor.editor.mini.is-focused)
     -0:00.4.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:00.4.0 skim:displayline (atom-text-editor.editor)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
atom-jade, v0.3.0
language-docker, v1.1.6
language-latex, v0.6.1
latex, v0.29.0
latexer, v0.3.0
linter-write-good, v0.6.1
skim-displayline, v0.0.1

# Dev
No dev packages
```

**Comment by shashankg7** [comment]
Hi. I am facing the same issue. 

Did you find any solution to it?
